### PR TITLE
Fixes labels/bad input/example input for Improve usability of the DriverAvailabilities Create Page #13

### LINKED ISSUE #32: Fix Incorrect interpreation of "day" field in DriverAvailability backend
In the backend code for DriverAvailability, there is currently an ambiguity.

The field `day` in the DriverAvailability entity should have been interpeted as a day of the week, e.g. `Monday`, Tuesday`, etc.

But in `src/test/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityControllerTests.java`

we see code like this:
```java
  DriverAvailability availability1 = DriverAvailability.builder()
                        .driverId(1)
                        .day("03/05/2024")
                        .startTime("10:30AM")
                        .endTime("2:30PM")
                        .notes("End for late lunch")
                        .build();
```

That part: `    .day("03/05/2024")` should probably be something like: `day("Monday")` indicating that the driver is available every Monday from 10:30AM to 2:30PM.   Not just on a specific day.

This should be changed throughout the code base anywhere this wrong assumption appears.  

Please also check places such as the fixtures in the frontend, as well as any frontend tests.

But certainly, at least, change it in  `src/test/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityControllerTests.java`

### PR DESCRIPTION
**Pull request by Tommygithubaccount123**
[DOKKU](https://tommy-dev.dokku-13.cs.ucsb.edu/)

Does part of EPIC issue [13](https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5/issues/13). 

Closes #32  (Made day of week a dropdown, only able to select day of week)

Note: Did not change driverId since we will remove this later on in the EPIC. Only front-end changes.

- The form labels are improved
- The bad input and missing input error messages are added and improved
- Example inputs on each form field
- Dropdown for choosing day instead of free form

BEFORE:
image

image

AFTER

image
image
image

Code modeled from `RideForm.js`

### CODE REVIEW

**Review by Ononymous — DISMISSED** [review]
LGTM

File: frontend/src/main/components/Driver/DriverAvailabilityForm.js [hunk 1]
```diff
@@ -11,7 +11,7 @@ function DriverAvailabilityForm({ initialContents, submitAction, buttonLabel = "
     } = useForm(
         { defaultValues: initialContents || {}, }
     );
-    // Stryker restore all
+    // Stryker enable all
```
Comment (pconrad) [inline frontend/src/main/components/Driver/DriverAvailabilityForm.js]:
```suggestion
    // Stryker restore all
```

It turns out that `    // Stryker enable all` isn't a thing.  We need to change all occurences of `// Stryker enable all` to `// Stryker restore all` as find them.

**Review by pconrad — CHANGES_REQUESTED** [review]
One small change needed.

Also, please deploy this on Dokku and link to the dokku deployment so we can test it more thoroughly.

**Comment by Tommygithubaccount123** [comment]
I added tests since the changing the stryker comment made the mutations happen. I added [dokku](https://tommy-dev.dokku-13.cs.ucsb.edu/) link in PR

@pconrad

File: frontend/src/main/components/Driver/DriverAvailabilityForm.js [hunk 2]
```diff
@@ -47,63 +47,85 @@ function DriverAvailabilityForm({ initialContents, submitAction, buttonLabel = "
...
-                <Form.Label htmlFor="notes">notes</Form.Label>
+                <Form.Label htmlFor="notes">Notes</Form.Label>
                 <Form.Control
                     data-testid={testIdPrefix + "-notes"}
                     id="notes"
                     type="text"
                     isInvalid={Boolean(errors.notes)}
                     {...register("notes", {
-                        required: "notes is required."
+                        required: "Notes are required."
```
Comment (andrewpengucsb) [inline frontend/src/main/components/Driver/DriverAvailabilityForm.js]: I must have not realized this when writing the issue, but small change...

I don't think that the notes field should be required since, there may be no need for a driver to add any notes.

**Review by andrewpengucsb — CHANGES_REQUESTED** [review]

File: frontend/src/main/components/Driver/DriverAvailabilityForm.js (hunk 2 above)
Comment (andrewpengucsb) [reply frontend/src/main/components/Driver/DriverAvailabilityForm.js]: Dont leave commented code

**Review by walexgreen — APPROVED** [review]
LGTM

**Review by andrewpengucsb — APPROVED** [review]
LGTM
