### PR TITLE
Fix BUG: Github repo link is hardcoded #18

### LINKED ISSUE #18: BUG: Github repo link is hardcoded
### Summary

When clicking the `Github` hyperlink on the footer, the link routes to a hardcoded github repo. Instead this should be dynamic and be based on the repo specified in the system info. By default the link can go to `proj-gauchoride` in the `ucsb-cs156` organization. This also requires the issue "FEATURE - expose commit infomation at /api/systemInfo" to be completed, since that issue adds the github repo to the system info.

### Expected Behavior

Clicking the hyperlink should go to the currently deployed application's github repo, with the default value (if the system info isnt set) of the main `proj-gauchoride` 

### Current / Observed Behavior

Clicking the hyperlink takes us to a s23 gauchoride repo

### Implementation Todos

- [ ] After the issue "FEATURE - expose commit infomation at /api/systemInfo" is completed, modify `Footer.js` to use the systeminfo instead of a hardcoded value.

### PR DESCRIPTION
**Pull request by Tommygithubaccount123**
[dokku](https://tommy-dev.dokku-13.cs.ucsb.edu)

When clicking the Github hyperlink on the footer, the link routes to a hardcoded github repo. Instead this should be dynamic and be based on the repo specified in the system info. By default the link can go to proj-gauchoride in the ucsb-cs156 organization. This also requires the issue "FEATURE - expose commit infomation at /api/systemInfo" to be completed, since that issue adds the github repo to the system info.

After the issue "FEATURE - expose commit infomation at /api/systemInfo" is completed, modify Footer.js to use the systeminfo instead of a hardcoded value.

UPDATE:
- resolved issues with incorrect testing and param usage

Closes #18

### CODE REVIEW

**Review by pconrad — CHANGES_REQUESTED** [review]
See hints here: 

https://ucsb-cs156-s24.slack.com/archives/C06RP83BA83/p1716676103256029

Also see code review below.

File: frontend/src/main/components/Nav/Footer.js [hunk 1]
```diff
@@ -1,8 +1,16 @@
...
 
 export default function Footer() {
+  const [repoUrl, setRepoUrl] = useState("");
+  useEffect(() => { 
+    fetch("/api/systemInfo")
+      // .then((res) => res.json())
+      .then((data) => {
+        setRepoUrl(data.sourceRepo);
+      });
+  }, []);
```
Comment (pconrad) [inline frontend/src/main/components/Nav/Footer.js]: Suggest removing all of this, and instead, pass systemInfo into the component in BasicLayout.js.

File: frontend/src/main/components/Nav/Footer.js [hunk 2]
```diff
@@ -1,8 +1,16 @@
+import { useEffect, useState } from "react";
 import { Container } from "react-bootstrap";
-
 export const space = " ";
 
 export default function Footer() {
```
Comment (pconrad) [inline frontend/src/main/components/Nav/Footer.js]:
```suggestion
export default function Footer({systemInfo}) {
```

File: frontend/src/main/components/Nav/Footer.js [hunk 3]
```diff
@@ -1,8 +1,16 @@
+import { useEffect, useState } from "react";
```
Comment (pconrad) [inline frontend/src/main/components/Nav/Footer.js]:
```suggestion

```

File: frontend/src/main/components/Nav/Footer.js [hunk 4]
```diff
@@ -26,7 +34,8 @@ export default function Footer() {
           {space}
           <a
             data-testid="footer-source-code-link"
-            href={"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-2"}
+            href={repoUrl}
+            // use api/systemInfo to get the repo URL
```
Comment (pconrad) [inline frontend/src/main/components/Nav/Footer.js]:
```suggestion
```

File: frontend/src/main/components/Nav/Footer.js [hunk 5]
```diff
@@ -26,7 +34,8 @@ export default function Footer() {
           {space}
           <a
             data-testid="footer-source-code-link"
-            href={"https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-2"}
+            href={repoUrl}
```
Comment (pconrad) [inline frontend/src/main/components/Nav/Footer.js]:
```suggestion
            href={systemInfo?.sourceRepo}
```

File: frontend/src/tests/components/Nav/Footer.test.js [hunk 6]
```diff
@@ -15,6 +19,16 @@ describe("Footer tests", () => {
...
+        axiosMock.onGet("/api/systemInfo").reply(200, {
+            "springH2ConsoleEnabled": true,
+            "showSwaggerUILink": true,
+            "startQtrYYYYQ": "20221",
+            "endQtrYYYYQ": "20222",
+            "sourceRepo": "https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5",
+            "commitMessage": "add missing values",
+            "commitId": "c65b37b",
+            "githubUrl": "https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5/commit/c65b37b"
+          })
```
Comment (pconrad) [inline frontend/src/tests/components/Nav/Footer.test.js]: You won't need to do the axiosMock if you make this a prop.

File: frontend/src/tests/components/Nav/Footer.test.js [hunk 7]
```diff
@@ -15,6 +19,16 @@ describe("Footer tests", () => {
...
         render(<Footer />)
```
Comment (pconrad) [inline frontend/src/tests/components/Nav/Footer.test.js]:
```suggestion
        const systemInfo = { sourceRepo: "https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5"};
        render(<Footer systemInfo={systemInfo} />)
```

File: frontend/src/tests/components/Nav/Footer.test.js [hunk 8]
```diff
@@ -24,10 +38,11 @@ describe("Footer tests", () => {
...
         );
-        expect(screen.getByTestId("footer-source-code-link")).toHaveAttribute(
-            "href",
-            "https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-2"
-        );
+        console.log(screen.getByTestId("footer-source-code-link"))
+        // expect(screen.getByTestId("footer-source-code-link")).toHaveAttribute(
+        //     "href",
+        //     "https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5"
+        // );
```
Comment (pconrad) [inline frontend/src/tests/components/Nav/Footer.test.js]:
```suggestion
        expect(screen.getByTestId("footer-source-code-link")).toHaveAttribute(
             "href",
             "https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-5"
         );
```

**Review by pconrad — CHANGES_REQUESTED** [review]
A few hints for getting this working.  

You'll also need to change BasicLayout.js to pass systemInfo into it (the same way it's passed into AppNavbar)

**Comment by Tommygithubaccount123** [comment]
The link doesn't show up now, I am not sure what is going on:
image

**Review by Ononymous — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM

**Comment by maidang111** [comment]
LGTM
